version: '3.2'
services:
  server:
    build: .
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - ./vpnserver/vpn_server.config:/vpnserver/vpn_server.config:rw
    restart: always
